allowed-perms:
  - riw.gui
  - cosmin.command.cosmetics

filler:
  material: "BLACK_STAINED_GLASS_PANE"
  custom_model_data: 0
  name: "&8" # "BLACK_STAINED_GLASS_PANE" RABBIT_FOOT 27104 invisible name for filler slots

gui:

  anyphone_home_collect:
    title: "§f稙뀀稤"
    size: 54
    buttons:
      check_button_home_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_home"
        design:
          material: DIAMOND
          name: "Close Collection"
          custom_model_data: 0

      retrieve_slot_home_collect:
        slot: [ 47, 49, 51 ]
        type: OUTPUT_SLOT
        action: REWARD_GET
        reward_group: dungeon_items


  anyphone_home:
    title: "§f稙稬稤"
    size: 54
    buttons:
      anyhome_open_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_home_collect"
        design:
          material: DIAMOND
          name: "Collect Dungeon Items"
          custom_model_data: 0


  anyphone_dungeon_one:
    title: "§f稙稧稤"
    size: 54
    buttons:
      dungeonone_submit_button:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: dungeonone_submit_slot
        check_item:
          reward_group: dungeon_items
        design:
          material: DIAMOND
          name: "Submit Dungeon Items"
          custom_model_data: 0

      dungeonone_submit_slot:
        slot: [ 49 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: dungeon_items

  anyphone_dungeon_two:
    title: "§f稙稥稤"
    size: 54
    buttons:
      dungeontwo_submit_button:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: dungeontwo_submit_slot
        check_item:
          reward_group: dungeon_items
        design:
          material: DIAMOND
          name: "Submit Dungeon Items"
          custom_model_data: 0

      dungeontwo_submit_slot:
        slot: [ 47, 49 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: dungeon_items


  anyphone_dungeon_three:
    title: "§f稙뀀稤"
    size: 54
    buttons:
      dungeonthree_submit_button:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: dungeonthree_submit_slot
        check_item:
          reward_group: dungeon_items
        design:
          material: DIAMOND
          name: "Submit Dungeon Items"
          custom_model_data: 0

      dungeonthree_submit_slot:
        slot: [ 47, 49, 51 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: dungeon_items




  anyphone_faction_collect:
    title: "§f稙뀀稤"
    size: 54
    buttons:
      check_button_faction_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_faction"
        design:
          material: DIAMOND
          name: "Close Collection"
          custom_model_data: 0

      retrieve_slot_faction_collect:
        slot: [ 47, 49, 51 ]
        type: OUTPUT_SLOT
        action: REWARD_GET
        reward_group: faction_items


  anyphone_faction:
    title: "§f稙稬稤"
    size: 54
    buttons:
      anyfaction_open_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_faction_collect"
        design:
          material: DIAMOND
          name: "Collect Faction Items"
          custom_model_data: 0


  anyphone_faction_submit:
    title: "§f稙稧稤"
    size: 54
    buttons:
      anyfaction_submit_button:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: anyfaction_submit_slot
        cost: 64
        check_item:
          reward_group: faction_items
        design:
          material: DIAMOND
          name: "Submit faction Items"
          custom_model_data: 0

      anyfaction_submit_slot:
        slot: [ 49 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: faction_items

  bananabuddy_widthdraw:
    title: "§f뀥뀧"
    size: 45
    buttons:

      bananapearl_collect_1:
        slot: [ 2 ]
        type: BUTTON
        action: GIVE
        output_item:
          mythic: banana_pearl
          amount: 1
        cost: 1
        design:
          material: RABBIT_FOOT
          name: "Withdraw β1"
          custom_model_data: 27142

      bananapearl_collect_5:
        slot: [ 3 ]
        type: BUTTON
        action: GIVE
        output_item:
          mythic: banana_pearl
          amount: 5
        cost:
          eco: 5
          payout: false
          scale_with_output: true
        design:
          material: RABBIT_FOOT
          name: "Withdraw β5"
          custom_model_data: 27143

      bananapearl_collect_15:
        slot: [ 4 ]
        type: BUTTON
        action: GIVE
        output_item:
          mythic: banana_pearl
          amount: 15
        cost:
          eco: 15
          payout: false
          scale_with_output: true
        design:
          material: RABBIT_FOOT
          name: "Withdraw β15"
          custom_model_data: 27144

      bananapearl_collect_50:
        slot: [ 5 ]
        type: BUTTON
        action: GIVE
        output_item:
          mythic: banana_pearl
          amount: 50
        cost:
          eco: 50
          payout: false
          scale_with_output: true
        design:
          material: RABBIT_FOOT
          name: "Withdraw β50"
          custom_model_data: 27145

      bananapearl_collect_100:
        slot: [ 6 ]
        type: BUTTON
        action: GIVE
        output_item:
          mythic: banana_pearl
          amount: 100
        cost:
          eco: 100
          payout: false
          scale_with_output: true
        design:
          material: RABBIT_FOOT
          name: "Withdraw β100"
          custom_model_data: 27146

      bananabuddy_deposit_button:
        slot: [ 20 ]
        type: BUTTON
        action: COMMAND
        logic: "player:bananabuddy_deposit"
        design:
          material: RABBIT_FOOT
          name: "Deposit"
          custom_model_data: 27115

      withdraw_animation_1:
        type: BUTTON
        slot: [ 12 ]
        design:
          material: "RABBIT_FOOT"
          custom_model_data: 27084
          name: "&8"

      withdraw_animation_2:
        type: BUTTON
        slot: [ 14 ]
        design:
          material: "RABBIT_FOOT"
          custom_model_data: 27089
          name: "&8"



  bananabuddy_deposit:
    title: "§f뀦뀧"
    size: 45
    buttons:

      loading_icon:
        type: BUTTON
        slot: [ 13 ]
        design:
          material: "RABBIT_FOOT"
          custom_model_data: 27090
          name: "&8"

      bananabuddy_withdraw_button:
        slot: [ 24 ]
        type: BUTTON
        action: COMMAND
        logic: "player:bananabuddy_widthdraw"
        design:
          material: RABBIT_FOOT
          name: "Withdraw"
          custom_model_data: 27116

      bananapearl_deposit:
        slot: [ 38, 39, 40, 41, 42 ]
        type: INPUT_SLOT
        action: CONSUME
        cost:
          eco: 1
          per_stack: true
          payout: true
        accepted_item:
          mythic: banana_pearl

      deposit_animation_1:
        type: BUTTON
        slot: [ 12 ]
        design:
          material: "RABBIT_FOOT"
          custom_model_data: 27109
          name: "&8"

      deposit_animation_2:
        type: BUTTON
        slot: [ 14 ]
        design:
          material: "RABBIT_FOOT"
          custom_model_data: 27114
          name: "&8"

  player_storage:
    title: "&eStorage Chest"
    size: 54
    buttons:
      storage:
        type: STORAGE_SLOT
        slot: [ 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25 ]

  homeshusk_buttons:
    title: "huskhomes"
    size: 54
    buttons:
      create_home_buttons:
        slot: [ 40 ]
        type: HUSKHOME_BUTTON
        action: CREATE
        cost: 20
        design:
          material: GRASS_BLOCK
          name: "&a&lCreate Home"
      home_buttons:
        slot: [ 10, 11, 12, 13, 14, 15, 16 ]
        type: HUSKHOME_BUTTON
        action: TELEPORT
        cost: 1
        design:
          material: ENDER_PEARL
          name: "&a%home_name%"
      delete_home_buttons:
        slot: [ 19, 20, 21, 22, 23, 24, 25 ]
        type: HUSKHOME_BUTTON
        action: DELETE
        cost: 0
        design:
          material: BARRIER
          name: "&cDelete &a%home_name%"
      epic_buttons:
        slot: [ 43 ]        # put one or more RTP pearls wherever you like
        type: HUSKHOME_BUTTON
        action: RANDOM_TELEPORT
        tel_world: new
        cost: 0
        design:
          material: LIGHT
          name: "&aRandom Teleport"

  death_chest:
    title: "&cDeath Chest"
    size: 54
    buttons:
      # Submit the Death Key (paper) to unlock a specific victim’s chest
      death_key_submit:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: death_key_submit_slot
        check_item:
          material: PAPER
          reward_group: death_items
        design:
          material: DIAMOND
          name: "&cSubmit Death Key"
          custom_model_data: 0

      # Where the player places their Death Key
      death_key_submit_slot:
        slot: [ 49 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          material: PAPER

  death_collect:
    title: "death collect"
    size: 54
    buttons:

      retrieve_slot_death_collect:
        slot: [ 45, 46, 47, 48, 50, 51 ]
        type: OUTPUT_SLOT
        action: REWARD_GET
        reward_group: death_items



