filler:
  material: "RABBIT_FOOT"
  custom_model_data: 27104
  name: "&8" # Gray invisible name for filler slots

gui:


  shop:
    title: "&6Item Shop"
    size: 27
    buttons:
      buy_diamond:
        slot: [11]
        type: BUTTON
        action: COMMAND
        logic: "minecraft:give %player% minecraft:diamond"
        cost: 25
        design:
          material: DIAMOND
          name: "&bBuy Diamond"
          custom_model_data: 0

      deposit_slot:
        slot: [13]
        type: INPUT_SLOT
        cost: 10


  # === GUI 1: Krobus ===
  krobus:
    title: "&cSpawn Menu"
    size: 27

    buttons:
      pig_button:
        slot: [20]
        type: BUTTON
        action: COMMAND
        logic: "minecraft:summon minecraft:pig"
        design:
          material: PIG_SPAWN_EGG
          name: "&dClick to spawn a pig!"
          custom_model_data: 0

      item_slot:
        slot: [13]
        type: INPUT_SLOT

  # === GUI 2: Interface ===
  interface:
    title: "&aInterface Menu"
    size: 54

    buttons:
      input_slot:
        slot: [22]
        type: INPUT_SLOT

      example_button:
        slot: [11]
        type: BUTTON
        action: COMMAND
        logic: "minecraft:give %player% minecraft:diamond"
        design:
          material: DIAMOND
          name: "&bGive yourself a diamond!"

  # === GUI 3: Enderlink ===
  enderlink:
    title: "§f稙稬稤"
    size: 54
    storage: true

    buttons:
      storage_slot:
        slot: [13, 14, 22, 23, 31, 32]
        type: INPUT_SLOT

      clear_button:
        slot: [49]
        type: BUTTON
        action: COMMAND
        logic: "minecraft:clear %player%"
        design:
          material: BARRIER
          name: "&cClear Storage"



poison:
  poison-world: "dungeon_build"
  poison-block: "minecraft:tripwire[attached=false,disarmed=true,east=true,north=false,powered=false,west=true]"


recipe-book-command: "enderlink"
