filler:
  material: "RABBIT_FOOT"
  custom_model_data: 27105
  name: "&8" # Gray invisible name for filler slots

gui:


  anyphone_home_collect:
    title: "§f稙뀀稤"
    size: 54
    buttons:
      check_button_home_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_home"
        design:
          material: DIAMOND
          name: "Collect Faction Items"
          custom_model_data: 0

      retrieve_slot_home_collect:
        slot: [ 47, 49, 51 ]
        type: OUTPUT_SLOT
        action: REWARD_GET
        reward_group: dungeon_items


  anyphone_home:
    title: "§f稙稬稤"
    size: 54
    buttons:
      anyhome_open_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_home_collect"
        design:
          material: DIAMOND
          name: "Collect Faction Items"
          custom_model_data: 0


  anyphone_dungeon_one:
    title: "§f稙稧稤"
    size: 54
    buttons:
      dungeonone_submit_button:
        slot: [ 19 ]
        type: CHECK_BUTTON
        slot_connection: dungeonone_submit_slot
        check_item:
          reward_group: dungeon_items
        design:
          material: DIAMOND
          name: "Submit Dungeon Items"
          custom_model_data: 0

      dungeonone_submit_slot:
        slot: [ 49 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: dungeon_items

  anyphone_dungeon_two:
    title: "§f稙稥稤"
    size: 54
    buttons:
      dungeontwo_submit_button:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: dungeontwo_submit_slot
        check_item:
          reward_group: dungeon_items
        design:
          material: DIAMOND
          name: "Submit Dungeon Items"
          custom_model_data: 0

      dungeontwo_submit_slot:
        slot: [ 47, 49 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: dungeon_items


  anyphone_dungeon_three:
    title: "§f稙뀀稤"
    size: 54
    buttons:
      dungeonthree_submit_button:
        slot: [ 52 ]
        type: CHECK_BUTTON
        slot_connection: dungeonthree_submit_slot
        check_item:
          reward_group: dungeon_items
        design:
          material: DIAMOND
          name: "Submit Dungeon Items"
          custom_model_data: 0

      dungeonthree_submit_slot:
        slot: [ 47, 49, 51 ]
        type: INPUT_SLOT
        action: CONSUME
        accepted_item:
          reward_group: dungeon_items




  anyphone_faction_collect:
    title: "§f稙뀀稤"
    size: 54
    buttons:
      check_button_faction_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_faction"
        design:
          material: DIAMOND
          name: "Close Collection"
          custom_model_data: 0

      retrieve_slot_faction_collect:
        slot: [ 47, 49, 51 ]
        type: OUTPUT_SLOT
        action: REWARD_GET
        reward_group: faction_items


  anyphone_faction:
    title: "§f稙稬稤"
    size: 54
    buttons:
      anyfaction_open_collect:
        slot: [ 52 ]
        type: BUTTON
        action: COMMAND
        logic: "player:anyphone_faction_collect"
        design:
          material: DIAMOND
          name: "Collect Faction Items"
          custom_model_data: 0

poison:
  poison-world: "dungeon_build"
  poison-block: "minecraft:tripwire[attached=false,disarmed=true,east=true,north=false,powered=false,west=true]"


recipe-book-command: "anyphone_home"
