name: HarambeCore
version: '1.0-SNAPSHOT'
main: net.anatomyworld.harambeCore.HarambeCore
api-version: '1.21'
description: A plugin for managing custom GUIs, reward groups, and item systems via MythicMobs.

depend: [MythicMobs, Vault]

commands:
  harambe:
    description: Core admin command for reload, reward mapping, and player reward management.
    usage: /harambe <reload|set rewardgroup|set reward|give reward>
    aliases: [md]
    permission: harambefd.admin

permissions:
  harambefd.admin:
    description: Allows access to all HarambeCore admin commands and GUI features.
    default: op
