name: HarambeCore
version: '1.0-SNAPSHOT'
main: net.anatomyworld.harambeCore.HarambeCore
api-version: '1.21'
description: A plugin for managing custom GUIs, items, and integration with DungeonMMO.

depend: [ProtocolLib, Vault]

commands:
  harambe:
    description: Plugin management, item commands, and GUI access.
    usage: /harambe <reload|give|set|GUI_NAME>
    aliases: [md]
    permission: harambefd.admin

permissions:
  harambefd.admin:
    description: Permission to use admin commands like reload, item/reward management, and access GUIs.
    default: op
